### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/practica-de-hilos-IMA-G#2]
[Practica hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-IMA-G/files/6513285/Practica.hilos.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19.4/20

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
